<?php

namespace Database\Seeders;

use App\Models\MediaAsset;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MediaInstitutionalRepositorySeeder extends Seeder
{
    public function run(): void
    {
        $teacher = User::role('teacher')->first() ?? User::factory()->create();

        $samples = [
            // TOEFL (15 assets)
            // Listening Audio x5
            ['title' => 'TOEFL Listening: Academic Advising Session Dialogue', 'type' => 'audio', 'exam_type' => 'toefl', 'category' => 'Listening Audio', 'sub_category' => 'Dialogue', 'path' => 'media/toefl_audio_advising.mp3', 'mime' => 'audio/mp3', 'size' => 1420000, 'desc' => 'Student and professor academic advising session dialogue audio transcript.'],
            ['title' => 'TOEFL Listening: Oceanography Deep-Sea Biology Lecture', 'type' => 'audio', 'exam_type' => 'toefl', 'category' => 'Listening Audio', 'sub_category' => 'Lecture', 'path' => 'media/toefl_audio_biology.mp3', 'mime' => 'audio/mp3', 'size' => 2150000, 'desc' => 'Professor lecture on hydrothermal vent organism adaptations.'],
            ['title' => 'TOEFL Listening: Astronomy Planetary Motion Monologue', 'type' => 'audio', 'exam_type' => 'toefl', 'category' => 'Listening Audio', 'sub_category' => 'Lecture', 'path' => 'media/toefl_audio_astronomy.mp3', 'mime' => 'audio/mp3', 'size' => 1980000, 'desc' => 'Lecture transcript detailing geocentric vs heliocentric astronomical models.'],
            ['title' => 'TOEFL Listening: Campus Housing & Dormitory Inquiry', 'type' => 'audio', 'exam_type' => 'toefl', 'category' => 'Listening Audio', 'sub_category' => 'Conversation', 'path' => 'media/toefl_audio_housing.mp3', 'mime' => 'audio/mp3', 'size' => 1250000, 'desc' => 'Student inquiry dialogue regarding university housing reservations.'],
            ['title' => 'TOEFL Listening: Archaeology Artifact Conservation Seminar', 'type' => 'audio', 'exam_type' => 'toefl', 'category' => 'Listening Audio', 'sub_category' => 'Seminar', 'path' => 'media/toefl_audio_archaeology.mp3', 'mime' => 'audio/mp3', 'size' => 1890000, 'desc' => 'Seminar discussion on ancient pottery carbon isotope preservation.'],

            // Reading PDF x5
            ['title' => 'TOEFL Reading PDF: Volcanic Ash & Granite Geological Formations', 'type' => 'pdf', 'exam_type' => 'toefl', 'category' => 'Reading PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/toefl_reading_geology.pdf', 'mime' => 'application/pdf', 'size' => 450000, 'desc' => 'Passage document outlining volcanic plateaus and magma solidification.'],
            ['title' => 'TOEFL Reading PDF: Early Agricultural Settlement & Irrigation Systems', 'type' => 'pdf', 'exam_type' => 'toefl', 'category' => 'Reading PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/toefl_reading_agriculture.pdf', 'mime' => 'application/pdf', 'size' => 520000, 'desc' => 'Academic passage describing Mesopotamian grain cultivation.'],
            ['title' => 'TOEFL Reading PDF: Glacial Retreat & Earth Orbital Eccentricity', 'type' => 'pdf', 'exam_type' => 'toefl', 'category' => 'Reading PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/toefl_reading_glaciation.pdf', 'mime' => 'application/pdf', 'size' => 610000, 'desc' => 'Reference document detailing ice age solar radiation cycles.'],
            ['title' => 'TOEFL Reading PDF: Prehistoric Hominid Diet Carbon Isotope Analysis', 'type' => 'pdf', 'exam_type' => 'toefl', 'category' => 'Reading PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/toefl_reading_hominid.pdf', 'mime' => 'application/pdf', 'size' => 480000, 'desc' => 'Research paper on dental fossil isotope diet reconstruction.'],
            ['title' => 'TOEFL Reading PDF: Industrial Automation & Skilled Labor Shifts', 'type' => 'pdf', 'exam_type' => 'toefl', 'category' => 'Reading PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/toefl_reading_automation.pdf', 'mime' => 'application/pdf', 'size' => 390000, 'desc' => 'Economic analysis of factory automation and maintenance workforce.'],

            // Reading Images x5
            ['title' => 'TOEFL Diagram: Hydrothermal Vent Ecosystem Cross-Section', 'type' => 'image', 'exam_type' => 'toefl', 'category' => 'Reading Images', 'sub_category' => 'Diagram', 'path' => '/storage/images/toefl_diagram_vent.jpg', 'mime' => 'image/jpeg', 'size' => 380000, 'desc' => 'Illustration of ocean floor hydrothermal vents and chemosynthesis.'],
            ['title' => 'TOEFL Map: Ancient Mesopotamian Irrigation Canal Network', 'type' => 'image', 'exam_type' => 'toefl', 'category' => 'Reading Images', 'sub_category' => 'Map', 'path' => '/storage/images/toefl_map_mesopotamia.jpg', 'mime' => 'image/jpeg', 'size' => 410000, 'desc' => 'Topographical map of Tigris-Euphrates river agricultural canals.'],
            ['title' => 'TOEFL Chart: Earth Orbital Eccentricity Cycle Diagram', 'type' => 'image', 'exam_type' => 'toefl', 'category' => 'Reading Images', 'sub_category' => 'Chart', 'path' => '/storage/images/toefl_chart_orbit.jpg', 'mime' => 'image/jpeg', 'size' => 290000, 'desc' => 'Diagram showing Milankovitch cycles and axial tilt variations.'],
            ['title' => 'TOEFL Diagram: Solar Radiation Photosynthesis Mechanism', 'type' => 'image', 'exam_type' => 'toefl', 'category' => 'Reading Images', 'sub_category' => 'Diagram', 'path' => '/storage/images/toefl_diagram_photo.jpg', 'mime' => 'image/jpeg', 'size' => 340000, 'desc' => 'Infographic detailing light energy conversion in plant chloroplasts.'],
            ['title' => 'TOEFL Chart: Industrial Automation Employment Trend Chart', 'type' => 'image', 'exam_type' => 'toefl', 'category' => 'Reading Images', 'sub_category' => 'Chart', 'path' => '/storage/images/toefl_chart_labor.jpg', 'mime' => 'image/jpeg', 'size' => 270000, 'desc' => 'Bar graph comparing manual vs technical labor ratios over decades.'],

            // TOEIC (40 assets)
            // Part 1 Images x10
            ['title' => 'TOEIC Part 1 Photo: Executive Office Desk Document Review', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Office', 'path' => '/storage/images/toeic_part1_office.jpg', 'mime' => 'image/jpeg', 'size' => 310000, 'desc' => 'Photograph of an executive reviewing paperwork at a wooden desk.'],
            ['title' => 'TOEIC Part 1 Photo: Corporate Conference Room Discussion', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Meeting', 'path' => '/storage/images/toeic_part1_meeting.jpg', 'mime' => 'image/jpeg', 'size' => 350000, 'desc' => 'Photograph of team members seated around a conference table.'],
            ['title' => 'TOEIC Part 1 Photo: Commercial Shipping Warehouse Logistics', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Warehouse', 'path' => '/storage/images/toeic_part1_warehouse.jpg', 'mime' => 'image/jpeg', 'size' => 420000, 'desc' => 'Photograph of inventory boxes stacked on wooden pallets in warehouse.'],
            ['title' => 'TOEIC Part 1 Photo: Urban Pedestrian Sidewalk Street Scene', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Outdoor', 'path' => '/storage/images/toeic_part1_street.jpg', 'mime' => 'image/jpeg', 'size' => 380000, 'desc' => 'Photograph of pedestrians walking alongside commercial storefronts.'],
            ['title' => 'TOEIC Part 1 Photo: Chemical Laboratory Equipment Bench', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Lab', 'path' => '/storage/images/toeic_part1_lab.jpg', 'mime' => 'image/jpeg', 'size' => 390000, 'desc' => 'Photograph of a scientist adjusting lab equipment on a bench.'],
            ['title' => 'TOEIC Part 1 Photo: Airport Terminal Gate Seating Area', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Travel', 'path' => '/storage/images/toeic_part1_airport.jpg', 'mime' => 'image/jpeg', 'size' => 330000, 'desc' => 'Photograph of passengers waiting at an airport boarding gate.'],
            ['title' => 'TOEIC Part 1 Photo: Retail Department Store Display Shelf', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Retail', 'path' => '/storage/images/toeic_part1_retail.jpg', 'mime' => 'image/jpeg', 'size' => 340000, 'desc' => 'Photograph of merchandise arranged neatly on retail shelves.'],
            ['title' => 'TOEIC Part 1 Photo: Industrial Construction Site Crane', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Construction', 'path' => '/storage/images/toeic_part1_construction.jpg', 'mime' => 'image/jpeg', 'size' => 450000, 'desc' => 'Photograph of workers operating machinery on a building site.'],
            ['title' => 'TOEIC Part 1 Photo: Restaurant Dining Room Table Setting', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Hospitality', 'path' => '/storage/images/toeic_part1_restaurant.jpg', 'mime' => 'image/jpeg', 'size' => 360000, 'desc' => 'Photograph of set dining tables inside a modern restaurant.'],
            ['title' => 'TOEIC Part 1 Photo: IT Server Room Network Cable Cabinet', 'type' => 'image', 'exam_type' => 'toeic', 'category' => 'Part 1 Images', 'sub_category' => 'Tech', 'path' => '/storage/images/toeic_part1_server.jpg', 'mime' => 'image/jpeg', 'size' => 410000, 'desc' => 'Photograph of an engineer inspecting server network cables.'],

            // Part 2 Audio x5
            ['title' => 'TOEIC Part 2 Audio: Quarterly Sales Conference Location Inquiry', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 2 Audio', 'sub_category' => 'Question Response', 'path' => 'media/toeic_part2_q1.mp3', 'mime' => 'audio/mp3', 'size' => 450000, 'desc' => 'Spoken question: Where will the quarterly sales conference be held?'],
            ['title' => 'TOEIC Part 2 Audio: Project Proposal Deadline Submission Time', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 2 Audio', 'sub_category' => 'Question Response', 'path' => 'media/toeic_part2_q2.mp3', 'mime' => 'audio/mp3', 'size' => 420000, 'desc' => 'Spoken question: When is the project proposal deadline?'],
            ['title' => 'TOEIC Part 2 Audio: Office Supplies Requisition Responsibility', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 2 Audio', 'sub_category' => 'Question Response', 'path' => 'media/toeic_part2_q3.mp3', 'mime' => 'audio/mp3', 'size' => 480000, 'desc' => 'Spoken question: Who is responsible for ordering office supplies?'],
            ['title' => 'TOEIC Part 2 Audio: Team Catering Lunch Order Preference', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 2 Audio', 'sub_category' => 'Question Response', 'path' => 'media/toeic_part2_q4.mp3', 'mime' => 'audio/mp3', 'size' => 410000, 'desc' => 'Spoken question: Should we order lunch now or wait until everyone arrives?'],
            ['title' => 'TOEIC Part 2 Audio: Contract Legal Review Delay Reason', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 2 Audio', 'sub_category' => 'Question Response', 'path' => 'media/toeic_part2_q5.mp3', 'mime' => 'audio/mp3', 'size' => 510000, 'desc' => 'Spoken question: Why hasn\'t the revised contract been signed yet?'],

            // Part 3 Conversations x5
            ['title' => 'TOEIC Part 3 Audio: Office Color Printer Paper Jam Problem', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 3 Conversations', 'sub_category' => 'Dialogue', 'path' => 'media/toeic_part3_printer.mp3', 'mime' => 'audio/mp3', 'size' => 1100000, 'desc' => 'Two colleagues discussing a paper feed jam on the second floor printer.'],
            ['title' => 'TOEIC Part 3 Audio: Logistics Inventory Warehouse Orientation', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 3 Conversations', 'sub_category' => 'Dialogue', 'path' => 'media/toeic_part3_warehouse.mp3', 'mime' => 'audio/mp3', 'size' => 1250000, 'desc' => 'Dialogue between HR manager and new warehouse supervisor.'],
            ['title' => 'TOEIC Part 3 Audio: Product Catalog Discounted Bulk Price Inquiry', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 3 Conversations', 'sub_category' => 'Dialogue', 'path' => 'media/toeic_part3_catalog.mp3', 'mime' => 'audio/mp3', 'size' => 1340000, 'desc' => 'Sales representative offering bulk discount catalog to a client.'],
            ['title' => 'TOEIC Part 3 Audio: Hotel Housekeeping Towel Service Request', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 3 Conversations', 'sub_category' => 'Dialogue', 'path' => 'media/toeic_part3_hotel.mp3', 'mime' => 'audio/mp3', 'size' => 980000, 'desc' => 'Guest calling front desk regarding unfulfilled housekeeping request.'],
            ['title' => 'TOEIC Part 3 Audio: IT Software Upgrade & System Server Migration', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 3 Conversations', 'sub_category' => 'Dialogue', 'path' => 'media/toeic_part3_software.mp3', 'mime' => 'audio/mp3', 'size' => 1420000, 'desc' => 'Systems admin discussing server maintenance schedule with department lead.'],

            // Part 4 Talks x5
            ['title' => 'TOEIC Part 4 Audio: Flight Departure Gate Boarding Announcement', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 4 Talks', 'sub_category' => 'Announcement', 'path' => 'media/toeic_part4_flight.mp3', 'mime' => 'audio/mp3', 'size' => 850000, 'desc' => 'Airport announcement for passengers boarding Flight 408 to Chicago.'],
            ['title' => 'TOEIC Part 4 Audio: Corporate Parking Garage Maintenance Closure', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 4 Talks', 'sub_category' => 'Announcement', 'path' => 'media/toeic_part4_parking.mp3', 'mime' => 'audio/mp3', 'size' => 920000, 'desc' => 'Corporate memo announcement regarding weekend parking garage repairs.'],
            ['title' => 'TOEIC Part 4 Audio: Metro Area Heavy Rainstorm Weather Report', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 4 Talks', 'sub_category' => 'Radio Broadcast', 'path' => 'media/toeic_part4_weather.mp3', 'mime' => 'audio/mp3', 'size' => 780000, 'desc' => 'Radio weather forecast predicting rainstorms and wind gusts.'],
            ['title' => 'TOEIC Part 4 Audio: Museum Exhibit Tour & Gift Shop Refreshments', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 4 Talks', 'sub_category' => 'Guided Tour', 'path' => 'media/toeic_part4_museum.mp3', 'mime' => 'audio/mp3', 'size' => 1050000, 'desc' => 'Tour guide conclusion inviting visitors to gift shop refreshments.'],
            ['title' => 'TOEIC Part 4 Audio: Cybersecurity Data Protocol Workshop Presentation', 'type' => 'audio', 'exam_type' => 'toeic', 'category' => 'Part 4 Talks', 'sub_category' => 'Presentation', 'path' => 'media/toeic_part4_cybersecurity.mp3', 'mime' => 'audio/mp3', 'size' => 1490000, 'desc' => 'Workshop presentation on data protection protocols for corporate staff.'],

            // Part 5 References x5
            ['title' => 'TOEIC Part 5 Ref: Financial Report Deadline Submission Rules', 'type' => 'pdf', 'exam_type' => 'toeic', 'category' => 'Part 5 References', 'sub_category' => 'Policy', 'path' => 'media/toeic_part5_deadline.pdf', 'mime' => 'application/pdf', 'size' => 180000, 'desc' => 'Prepositional usage guide for submission deadlines.'],
            ['title' => 'TOEIC Part 5 Ref: Workplace Adverb & Adjective Usage Matrix', 'type' => 'pdf', 'exam_type' => 'toeic', 'category' => 'Part 5 References', 'sub_category' => 'Grammar Chart', 'path' => 'media/toeic_part5_adverbs.pdf', 'mime' => 'application/pdf', 'size' => 220000, 'desc' => 'Reference sheet on modifier forms in business correspondence.'],
            ['title' => 'TOEIC Part 5 Ref: Technical Compatibility Preposition Guide', 'type' => 'pdf', 'exam_type' => 'toeic', 'category' => 'Part 5 References', 'sub_category' => 'Grammar Chart', 'path' => 'media/toeic_part5_prepositions.pdf', 'mime' => 'application/pdf', 'size' => 195000, 'desc' => 'Collocation reference for compatible with, competent in, comparable to.'],
            ['title' => 'TOEIC Part 5 Ref: Employee Tuition Reimbursement Policy', 'type' => 'pdf', 'exam_type' => 'toeic', 'category' => 'Part 5 References', 'sub_category' => 'Policy', 'path' => 'media/toeic_part5_tuition.pdf', 'mime' => 'application/pdf', 'size' => 240000, 'desc' => 'HR policy outline on prior supervisor approval.'],
            ['title' => 'TOEIC Part 5 Ref: Conjunction & Preposition Contrast Guide', 'type' => 'pdf', 'exam_type' => 'toeic', 'category' => 'Part 5 References', 'sub_category' => 'Grammar Chart', 'path' => 'media/toeic_part5_conjunctions.pdf', 'mime' => 'application/pdf', 'size' => 210000, 'desc' => 'Rules for Despite vs Although vs In spite of in business sentences.'],

            // Part 6 Passages x5
            ['title' => 'TOEIC Part 6 Passage: Commercial Office Relocation Notice Email', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 6 Passages', 'sub_category' => 'Email', 'path' => 'media/toeic_part6_relocation.txt', 'mime' => 'text/plain', 'size' => 1500, 'content_text' => 'Dear Valued Client, We are pleased to announce that our main office is relocating to a larger facility next month. Phone numbers will remain unchanged.', 'desc' => 'Passage text for business relocation email completion.'],
            ['title' => 'TOEIC Part 6 Passage: Shipping Delay & Dispatch Status Memo', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 6 Passages', 'sub_category' => 'Memo', 'path' => 'media/toeic_part6_shipping.txt', 'mime' => 'text/plain', 'size' => 1650, 'content_text' => 'To All Customers: We experienced temporary shipping delays last week due to severe weather. However, all pending orders have now been dispatched.', 'desc' => 'Passage text for shipping dispatch status memo.'],
            ['title' => 'TOEIC Part 6 Passage: Engineering Team Eco-Friendly Patents Update', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 6 Passages', 'sub_category' => 'Newsletter', 'path' => 'media/toeic_part6_patents.txt', 'mime' => 'text/plain', 'size' => 1800, 'content_text' => 'Corporate Update: Since 2018, our engineering team has registered over fifty eco-friendly patents, solidifying our leadership in green technology.', 'desc' => 'Corporate newsletter announcement text.'],
            ['title' => 'TOEIC Part 6 Passage: Mandatory Employee Safety Orientation Letter', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 6 Passages', 'sub_category' => 'Letter', 'path' => 'media/toeic_part6_safety.txt', 'mime' => 'text/plain', 'size' => 1400, 'content_text' => 'Notice to Staff: All employees are required to attend a mandatory safety orientation seminar in the auditorium next Tuesday morning.', 'desc' => 'Internal HR safety seminar letter.'],
            ['title' => 'TOEIC Part 6 Passage: IT Infrastructure Upgrade Maintenance Announcement', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 6 Passages', 'sub_category' => 'Notice', 'path' => 'media/toeic_part6_upgrade.txt', 'mime' => 'text/plain', 'size' => 1550, 'content_text' => 'IT System Alert: Network maintenance is scheduled for Sunday midnight. Database services will resume normal operation by 6:00 AM Monday.', 'desc' => 'IT alert notice for server maintenance.'],

            // Part 7 Reading x5
            ['title' => 'TOEIC Part 7 Reading: HR Remote Work Eligibility Criteria Policy', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 7 Reading', 'sub_category' => 'Corporate Policy', 'path' => 'media/toeic_part7_remotework.txt', 'mime' => 'text/plain', 'size' => 2200, 'content_text' => 'To: All Staff | From: HR Department | Subject: Revised Remote Work Policy. Effective September 1st, staff members must complete six months of continuous service prior to applying for telecommuting approval.', 'desc' => 'Corporate policy email on remote work eligibility.'],
            ['title' => 'TOEIC Part 7 Reading: BioTech Corp Gene-Editing Press Release', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 7 Reading', 'sub_category' => 'Press Release', 'path' => 'media/toeic_part7_biotech.txt', 'mime' => 'text/plain', 'size' => 2500, 'content_text' => 'For Immediate Release: BioTech Corp today unveiled its pioneering gene-editing platform at the international medical summit in Geneva.', 'desc' => 'Press release announcing innovative gene-editing platform.'],
            ['title' => 'TOEIC Part 7 Reading: European Market Expansion Analysis Document', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 7 Reading', 'sub_category' => 'Market Report', 'path' => 'media/toeic_part7_expansion.txt', 'mime' => 'text/plain', 'size' => 2400, 'content_text' => 'Document 2 (Market Analysis): Clinical trial approvals granted last month position BioTech Corp to enter European commercial markets by Q3.', 'desc' => 'Market analysis document for European commercial expansion.'],
            ['title' => 'TOEIC Part 7 Reading: Annual Client Service Survey Results Report', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 7 Reading', 'sub_category' => 'Survey Report', 'path' => 'media/toeic_part7_survey.txt', 'mime' => 'text/plain', 'size' => 2100, 'content_text' => 'Customer Feedback Summary: Over 92% of surveyed clients rated our technical support response times as excellent or above average.', 'desc' => 'Customer feedback report on technical support service.'],
            ['title' => 'TOEIC Part 7 Reading: Executive Travel Itinerary & Conference Schedule', 'type' => 'passage', 'exam_type' => 'toeic', 'category' => 'Part 7 Reading', 'sub_category' => 'Schedule', 'path' => 'media/toeic_part7_schedule.txt', 'mime' => 'text/plain', 'size' => 1950, 'content_text' => 'Travel Schedule for CEO: Flight departure Monday 9:00 AM. Keynote address Tuesday 10:30 AM in Grand Hall B.', 'desc' => 'Executive itinerary and keynote schedule.'],

            // IELTS (20 assets)
            // Listening Audio x5
            ['title' => 'IELTS Listening: University Housing Room Accommodation Inquiry', 'type' => 'audio', 'exam_type' => 'ielts', 'category' => 'Listening Audio', 'sub_category' => 'Social Dialogue', 'path' => 'media/ielts_listening_housing.mp3', 'mime' => 'audio/mp3', 'size' => 1480000, 'desc' => 'Student telephone inquiry to university housing office.'],
            ['title' => 'IELTS Listening: Campus Library Schedule & Weekend Hours Announcement', 'type' => 'audio', 'exam_type' => 'ielts', 'category' => 'Listening Audio', 'sub_category' => 'Information Talk', 'path' => 'media/ielts_listening_library.mp3', 'mime' => 'audio/mp3', 'size' => 950000, 'desc' => 'Librarian announcement on Friday 8 PM early closing time.'],
            ['title' => 'IELTS Listening: Campus Sports Center Pool Tile Refurbishment', 'type' => 'audio', 'exam_type' => 'ielts', 'category' => 'Listening Audio', 'sub_category' => 'Facility Talk', 'path' => 'media/ielts_listening_pool.mp3', 'mime' => 'audio/mp3', 'size' => 1100000, 'desc' => 'Notice regarding sports center pool maintenance.'],
            ['title' => 'IELTS Listening: Urban Wildflower Bee Population Lecture', 'type' => 'audio', 'exam_type' => 'ielts', 'category' => 'Listening Audio', 'sub_category' => 'Academic Lecture', 'path' => 'media/ielts_listening_bees.mp3', 'mime' => 'audio/mp3', 'size' => 2300000, 'desc' => 'Biology lecture on urban wildflower gardens and autumn bee survival.'],
            ['title' => 'IELTS Listening: Coastal Wetland Restoration Guest Lecture', 'type' => 'audio', 'exam_type' => 'ielts', 'category' => 'Listening Audio', 'sub_category' => 'Academic Lecture', 'path' => 'media/ielts_listening_wetland.mp3', 'mime' => 'audio/mp3', 'size' => 2100000, 'desc' => 'Environmental science lecture by Dr. Aris Thorne on coastal wetlands.'],

            // Reading Passage x5
            ['title' => 'IELTS Reading Passage: Geothermal Power & Hydrogen Sulfide Emissions', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Reading Passage', 'sub_category' => 'Academic Text', 'path' => 'media/ielts_reading_geothermal.txt', 'mime' => 'text/plain', 'size' => 2800, 'content_text' => 'While geothermal power generates substantially lower carbon emissions than fossil fuels, trace amounts of hydrogen sulfide and carbon dioxide are vented during steam extraction.', 'desc' => 'Academic passage evaluating environmental impacts of geothermal energy.'],
            ['title' => 'IELTS Reading Passage: Ancient Mesopotamian Clay Accounting Tablets', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Reading Passage', 'sub_category' => 'History Text', 'path' => 'media/ielts_reading_claytablets.txt', 'mime' => 'text/plain', 'size' => 3100, 'content_text' => 'Paragraph B details how ancient Mesopotamians built clay tablets for financial accounting, trade records, and legal contracts.', 'desc' => 'Historical analysis of early administrative record-keeping.'],
            ['title' => 'IELTS Reading Passage: Ocean Acidification & Coral Carbonate Skeletons', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Reading Passage', 'sub_category' => 'Marine Biology', 'path' => 'media/ielts_reading_corals.txt', 'mime' => 'text/plain', 'size' => 2950, 'content_text' => 'Increased carbonic acid concentration reduces available carbonate ions, hindering corals from building calcium carbonate skeletons.', 'desc' => 'Marine biology research on ocean acidification effects on reefs.'],
            ['title' => 'IELTS Reading Passage: Mysterious Voynich Cipher Manuscript Acquisition', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Reading Passage', 'sub_category' => 'Historical Mystery', 'path' => 'media/ielts_reading_voynich.txt', 'mime' => 'text/plain', 'size' => 2600, 'content_text' => 'In 1912, rare book dealer Wilfrid Voynich acquired the mysterious cipher manuscript from a Jesuit college near Rome.', 'desc' => 'Text passage discussing the origin and discovery of the Voynich manuscript.'],
            ['title' => 'IELTS Reading Passage: Renewable Energy Subsidies & Grid Modernization', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Reading Passage', 'sub_category' => 'Energy Economics', 'path' => 'media/ielts_reading_subsidies.txt', 'mime' => 'text/plain', 'size' => 3200, 'content_text' => 'Subsidies must transition from initial deployment incentives toward grid modernization and storage infrastructure.', 'desc' => 'Energy policy analysis on government subsidy allocation.'],

            // Writing Images x5
            ['title' => 'IELTS Task 1 Line Graph: Renewable Energy Share (2010–2020)', 'type' => 'image', 'exam_type' => 'ielts', 'category' => 'Writing Images', 'sub_category' => 'Line Graph', 'path' => '/storage/images/ielts_task1_linegraph.jpg', 'mime' => 'image/jpeg', 'size' => 450000, 'desc' => 'Line graph showing renewable energy share trends in 5 countries.'],
            ['title' => 'IELTS Task 1 Diagram: Seawater Desalination Industrial Process', 'type' => 'image', 'exam_type' => 'ielts', 'category' => 'Writing Images', 'sub_category' => 'Process Diagram', 'path' => '/storage/images/ielts_task1_desalination.jpg', 'mime' => 'image/jpeg', 'size' => 520000, 'desc' => 'Process flow diagram of reverse osmosis seawater desalination.'],
            ['title' => 'IELTS Task 1 Bar Chart: University Graduate Employment Rates by Sector', 'type' => 'image', 'exam_type' => 'ielts', 'category' => 'Writing Images', 'sub_category' => 'Bar Chart', 'path' => '/storage/images/ielts_task1_barchart.jpg', 'mime' => 'image/jpeg', 'size' => 410000, 'desc' => 'Bar chart comparing graduate employment in tech, health, and finance.'],
            ['title' => 'IELTS Task 1 Pie Chart: Household Energy Usage Breakdown', 'type' => 'image', 'exam_type' => 'ielts', 'category' => 'Writing Images', 'sub_category' => 'Pie Chart', 'path' => '/storage/images/ielts_task1_piechart.jpg', 'mime' => 'image/jpeg', 'size' => 380000, 'desc' => 'Pie chart showing heating, cooling, and appliance energy proportions.'],
            ['title' => 'IELTS Task 1 Flowchart: Paper Recycling & De-inking Industrial Stages', 'type' => 'image', 'exam_type' => 'ielts', 'category' => 'Writing Images', 'sub_category' => 'Flowchart', 'path' => '/storage/images/ielts_task1_recycling.jpg', 'mime' => 'image/jpeg', 'size' => 470000, 'desc' => 'Flowchart detailing collection, pulping, de-inking, and rolling.'],

            // Speaking Cue Cards x5
            ['title' => 'IELTS Speaking Cue Card: Memorable Public Transport Journey', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Speaking Cue Cards', 'sub_category' => 'Part 2 Cue Card', 'path' => 'media/ielts_speaking_transport.txt', 'mime' => 'text/plain', 'size' => 1100, 'content_text' => 'Describe a memorable journey you took by public transport. You should say: where you went, what transport you used, who you went with, and explain why it was memorable.', 'desc' => 'Cue card prompt for public transport journey.'],
            ['title' => 'IELTS Speaking Cue Card: Skill You Would Like to Learn', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Speaking Cue Cards', 'sub_category' => 'Part 2 Cue Card', 'path' => 'media/ielts_speaking_skill.txt', 'mime' => 'text/plain', 'size' => 1250, 'content_text' => 'Describe a skill you would like to learn in the future. You should say: what the skill is, why you want to learn it, how you plan to learn it, and explain how it will benefit your career.', 'desc' => 'Cue card prompt for future professional skill.'],
            ['title' => 'IELTS Speaking Cue Card: Environmental Protection Project', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Speaking Cue Cards', 'sub_category' => 'Part 2 Cue Card', 'path' => 'media/ielts_speaking_environment.txt', 'mime' => 'text/plain', 'size' => 1150, 'content_text' => 'Describe an environmental protection project in your city. You should say: what the project is, who organized it, what actions were taken, and explain its impact.', 'desc' => 'Cue card prompt for urban environmental initiative.'],
            ['title' => 'IELTS Speaking Cue Card: Traditional Festival Celebration', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Speaking Cue Cards', 'sub_category' => 'Part 2 Cue Card', 'path' => 'media/ielts_speaking_festival.txt', 'mime' => 'text/plain', 'size' => 1200, 'content_text' => 'Describe a traditional festival celebrated in your country. You should say: when it occurs, what people do, what special foods are eaten, and explain why you enjoy it.', 'desc' => 'Cue card prompt for cultural festival.'],
            ['title' => 'IELTS Speaking Cue Card: Influential Educator or Teacher', 'type' => 'passage', 'exam_type' => 'ielts', 'category' => 'Speaking Cue Cards', 'sub_category' => 'Part 2 Cue Card', 'path' => 'media/ielts_speaking_teacher.txt', 'mime' => 'text/plain', 'size' => 1180, 'content_text' => 'Describe a teacher who had a positive influence on your education. You should say: who the teacher was, what subject they taught, how they helped you, and explain why they were special.', 'desc' => 'Cue card prompt for influential educator.'],

            // Placement Test (3 assets)
            ['title' => 'Placement Diagnostic Passage: Past Perfect Action Sequence Text', 'type' => 'passage', 'exam_type' => 'placement', 'category' => 'Passages', 'sub_category' => 'Diagnostic', 'path' => 'media/placement_passage_pastperfect.txt', 'mime' => 'text/plain', 'size' => 1300, 'content_text' => 'She had lived in London for five years before moving to Paris in 2020.', 'desc' => 'Diagnostic passage text for A2/B1 streaming.'],
            ['title' => 'Placement Diagnostic Diagram: Level Streaming CEFR Chart', 'type' => 'image', 'exam_type' => 'placement', 'category' => 'Images', 'sub_category' => 'Diagram', 'path' => '/storage/images/placement_cefr_chart.jpg', 'mime' => 'image/jpeg', 'size' => 290000, 'desc' => 'Reference infographic for CEFR level streaming scale A1 to C1.'],
            ['title' => 'Placement Diagnostic Reading PDF: Multi-Level Assessment Guide', 'type' => 'pdf', 'exam_type' => 'placement', 'category' => 'PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/placement_assessment_guide.pdf', 'mime' => 'application/pdf', 'size' => 310000, 'desc' => 'Diagnostic evaluation rubric document.'],

            // Grammar (3 assets)
            ['title' => 'Grammar Infographic: Passive Voice Sentence Construction Chart', 'type' => 'image', 'exam_type' => 'grammar', 'category' => 'Images', 'sub_category' => 'Grammar Chart', 'path' => '/storage/images/grammar_passive_chart.jpg', 'mime' => 'image/jpeg', 'size' => 320000, 'desc' => 'Visual infographic explaining active vs passive voice transformations.'],
            ['title' => 'Grammar Infographic: Third Conditional If-Clause Formula', 'type' => 'image', 'exam_type' => 'grammar', 'category' => 'Images', 'sub_category' => 'Grammar Chart', 'path' => '/storage/images/grammar_conditional_chart.jpg', 'mime' => 'image/jpeg', 'size' => 300000, 'desc' => 'Visual breakdown of third conditional structure and past perfect usage.'],
            ['title' => 'Grammar Reference PDF: Relative Pronouns & Defining Clauses', 'type' => 'pdf', 'exam_type' => 'grammar', 'category' => 'PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/grammar_relative_clauses.pdf', 'mime' => 'application/pdf', 'size' => 260000, 'desc' => 'Grammar reference paper on who vs which vs whose.'],

            // Vocabulary (3 assets)
            ['title' => 'Vocabulary Infographic: Academic Word List (AWL) Collocations', 'type' => 'image', 'exam_type' => 'vocabulary', 'category' => 'Images', 'sub_category' => 'Vocabulary Chart', 'path' => '/storage/images/vocab_awl_collocations.jpg', 'mime' => 'image/jpeg', 'size' => 340000, 'desc' => 'Visual chart showing high-frequency academic verb-noun collocations.'],
            ['title' => 'Vocabulary Infographic: Formal Academic Synonyms & Roots', 'type' => 'image', 'exam_type' => 'vocabulary', 'category' => 'Images', 'sub_category' => 'Vocabulary Chart', 'path' => '/storage/images/vocab_synonyms_chart.jpg', 'mime' => 'image/jpeg', 'size' => 310000, 'desc' => 'Reference diagram replacing informal words with formal AWL terms.'],
            ['title' => 'Vocabulary PDF: AWL Sublist 1 to 10 Complete Vocabulary Guide', 'type' => 'pdf', 'exam_type' => 'vocabulary', 'category' => 'PDF', 'sub_category' => 'Reference PDF', 'path' => 'media/vocab_awl_guide.pdf', 'mime' => 'application/pdf', 'size' => 580000, 'desc' => 'Complete AWL word list reference booklet for academic preparation.'],
        ];

        foreach ($samples as $s) {
            MediaAsset::updateOrCreate(
                ['title' => $s['title']],
                [
                    'filename'        => basename($s['path']),
                    'original_name'   => $s['title'] . '.' . ($s['type'] === 'pdf' ? 'pdf' : ($s['type'] === 'audio' ? 'mp3' : ($s['type'] === 'passage' ? 'txt' : 'jpg'))),
                    'mime_type'       => $s['mime'],
                    'type'            => $s['type'],
                    'category'        => $s['category'],
                    'sub_category'    => $s['sub_category'],
                    'exam_type'       => $s['exam_type'],
                    'difficulty'      => 'medium',
                    'tags'            => ['institutional', 'starter', $s['exam_type'], strtolower(str_replace(' ', '_', $s['category']))],
                    'approval_status' => 'approved',
                    'version'         => '1.0',
                    'path'            => $s['path'],
                    'size'            => $s['size'],
                    'status'          => 'active',
                    'description'     => $s['desc'],
                    'content_text'    => $s['content_text'] ?? null,
                    'uploaded_by'     => $teacher->id,
                ]
            );
        }
    }
}
